#!/bin/sh
CNC_DIR=.

LD_LIBRARY_PATH=${CNC_DIR}:${LD_LIBRARY_PATH}
PATH=${CNC_DIR}:${PATH}
export USER=cnc
export CNC_IP=`cat settings.xml |grep kernel_ip| cut -d '>' -f 2|cut -d '<' -f 1`
echo set CNC_IP=$CNC_IP


phx-cnc-ui-mainform 2> logs/qform.last
