######################################################################
# Automatically generated by qmake (2.01a) ?? 28. ??? 16:42:16 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += . src
INCLUDEPATH += .
QT      += network

# Input
HEADERS += src/CXUdpManager.h src/CXWidget.h
SOURCES += src/CXUdpManager.cpp src/main.cpp src/CXWidget.cpp
FORMS += src/CXWidget.ui
