######################################################################
# Automatically generated by qmake (2.01a) ?? 21. ??? 11:03:34 2014
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += . GeneratedFiles
INCLUDEPATH += .

# Input
SOURCES += main.cpp
